#!/bin/bash

### BEGIN INIT INFO
# Provides:          midea2lox
# Required-Start:    $all
# Required-Stop::    $all
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Start midea2lox at boot time
# Description:       Manage the midea2lox daemon, bride between Midea-Cloud and Loxberry.
### END INIT INFO

#set -e
#set -u
#${DEBIAN_SCRIPT_DEBUG:+ set -v -x}


is_running() {
	/bin/ps -C "midea2lox.py" -opid= > /dev/null 2>&1
}

. /lib/lsb/init-functions
case "$1" in
        'start')
                if is_running; then
                    PID=`/bin/ps -C "midea2lox.py" -opid=`
                    echo "Midea2Lox is already running. PID: $PID"
                else
                    echo "Starting Midea2Lox.."
                if [ $EUID -eq 0 ]; then
                    cd REPLACEINSTALLFOLDER/data/plugins/REPLACEFOLDERNAME
                    su loxberry -c ./midea2lox.py > /dev/null 2>&1 &
                else
                    cd REPLACEINSTALLFOLDER/data/plugins/REPLACEFOLDERNAME
                    ./midea2lox.py > /dev/null 2>&1 &
                fi
                fi;;
        'stop')
                killall midea2lox.py;;
        'restart')
                $0 stop
                if is_running; then
                    echo "Unable to stop Midea2Lox, will not try to restart."
                    exit 1
                fi
                $0 start
                ;;
        '')
                $0 start
                ;;
        'status')
                if is_running; then
                    PID=`/bin/ps -C "midea2lox.py" -opid=`
                    echo "Midea2Lox is running. PID: $PID"
                else
                    echo "Midea2Lox is stopped."
                    exit 1
                fi;;
        *)
                echo "usage $0 start|stop|restart|status" ;;
				
esac

exit 0
